version: '3.8'

services:
  bot:
    env_file:
      - .env
    volumes:
      - ./src:/app
      - ./logs.log:/bot/logs.log
    build: .
    environment:
      - TOKEN=${TOKEN}
      - CHAT_ID=${CHAT_ID}
      - MESSAGE_THREAD_ID=${MESSAGE_THREAD_ID}

  redis:
    image: redis:alpine
    volumes:
      - redisdata:/root/redis

volumes:
  redisdata: